name: Contributors
on:
  schedule:
    - cron: '0 0 * * *'  # Updates daily at midnight UTC
  push:
    branches:
      - main

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cjdenio/contributor-activity@v1
        with:
          repo: Dhritikrishna123/Actify
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update contributors'
          file_pattern: README.md 